export const domesticAirports = {
  GMP: "서울/김포 (GMP)",
  ICN: "서울/인천 (ICN)",
  CJU: "제주 (CJU)",
  PUS: "부산/김해 (PUS)",
  TAE: "대구 (TAE)",
};

export const internationalAirports = {
  CDG: "샤를 드골 공항 (CDG)",
  NCE: "니스 코트다쥐르 공항 (NCE)",
  LYS: "리옹 생텍쥐페리 공항 (LYS)",
  MRS: "마르세유 프로방스 공항 (MRS)",
  BOD: "보르도 메리냑 공항 (BOD)",

  NRT: "나리타 국제공항 (NRT)",
  ITM: "이타미 공항 (ITM)",
  KIX: "간사이 국제공항 (KIX)",
  FUK: "후쿠오카 공항 (FUK)",
  CTS: "신치토세 공항 (CTS)",

  JFK: "존 F. 케네디 국제공항 (JFK)",
  LAX: "로스앤젤레스 국제공항 (LAX)",
  SFO: "샌프란시스코 국제공항 (SFO)",
  LAS: "해리 리드 국제공항 (LAS)",
  MIA: "마이애미 국제공항 (MIA)",

  LHR: "히드로 공항 (LHR)",
  EDI: "에든버러 공항 (EDI)",
  MAN: "맨체스터 공항 (MAN)",
  LPL: "리버풀 존 레논 공항 (LPL)",
  OXF: "옥스퍼드 공항 (OXF)",

  FCO: "피우미치노 공항 (FCO)",
  VCE: "베네치아 마르코폴로 공항 (VCE)",
  FLR: "피렌체 공항 (FLR)",
  MXP: "밀라노 말펜사 공항 (MXP)",
  NAP: "나폴리 국제공항 (NAP)",

  BCN: "바르셀로나 엘프라트 공항 (BCN)",
  MAD: "마드리드 바라하스 공항 (MAD)",
  SVQ: "세비야 공항 (SVQ)",
  GRX: "페데리코 가르시아 로르카 그라나다 공항 (GRX)",
  VLC: "발렌시아 공항 (VLC)",

  BER: "베를린 브란덴부르크 공항 (BER)",
  MUC: "뮌헨 공항 (MUC)",
  FRA: "프랑크푸르트 공항 (FRA)",
  HAM: "함부르크 공항 (HAM)",
  CGN: "쾰른 본 공항 (CGN)",

  PEK: "베이징 수도 국제공항 (PEK)",
  PVG: "상하이 푸둥 국제공항 (PVG)",
  CAN: "광저우 바이윈 국제공항 (CAN)",
  XIY: "시안 셴양 국제공항 (XIY)",
  CTU: "청두 솽류 국제공항 (CTU)",

  SYD: "시드니 킹스포드 스미스 공항 (SYD)",
  MEL: "멜버른 공항 (MEL)",
  BNE: "브리즈번 공항 (BNE)",
  PER: "퍼스 공항 (PER)",
  ADL: "애들레이드 공항 (ADL)",

  YYZ: "토론토 피어슨 국제공항 (YYZ)",
  YVR: "밴쿠버 국제공항 (YVR)",
  YUL: "몬트리올 트뤼도 국제공항 (YUL)",
  YQB: "퀘벡 시티 장 르사쥬 국제공항 (YQB)",
  YOW: "오타와 맥도날드 카르티에 국제공항 (YOW)",

  SVO: "셰레메티예보 국제공항 (SVO)",
  LED: "풀코보 공항 (LED)",
  OVB: "톨마체보 공항 (OVB)",
  KZN: "카잔 국제공항 (KZN)",
  AER: "소치 국제공항 (AER)",

  GIG: "리우데자네이루 갈레앙 국제공항 (GIG)",
  GRU: "상파울루 과룰류스 국제공항 (GRU)",
  BSB: "브라질리아 국제공항 (BSB)",
  SSA: "살바도르 국제공항 (SSA)",
  POA: "살가도 필류 국제공항 (POA)",

  DEL: "인디라 간디 국제공항 (DEL)",
  BOM: "차트라파티 시바지 마하라지 국제공항 (BOM)",
  AGR: "아그라 공항 (AGR)",
  JAI: "자이푸르 국제공항 (JAI)",
  BLR: "켐페고우다 국제공항 (BLR)",

  IST: "이스탄불 공항 (IST)",
  ESB: "에센보아 국제공항 (ESB)",
  AYT: "안탈리아 공항 (AYT)",
  NAV: "네브셰히르 카파도키아 공항 (NAV)",
  ADB: "이즈미르 아드난 멘데레스 공항 (ADB)",

  CAI: "카이로 국제공항 (CAI)",
  HBE: "알렉산드리아 보르그 엘 아랍 공항 (HBE)",
  LXR: "룩소르 국제공항 (LXR)",
  ASW: "아스완 국제공항 (ASW)",
  SSH: "샤름 엘 셰이크 국제공항 (SSH)",

  CPT: "케이프타운 국제공항 (CPT)",
  JNB: "OR 탐보 국제공항 (JNB)",
  DUR: "킹 샤카 국제공항 (DUR)",
  PRY: "원더붐 공항 (PRY)",
  PLZ: "포트 엘리자베스 공항 (PLZ)",

  BKK: "수완나품 공항 (BKK)",
  CNX: "치앙마이 국제공항 (CNX)",
  HKT: "푸켓 국제공항 (HKT)",
  UTP: "우타파오 국제공항 (UTP)",
  KBV: "끄라비 국제공항 (KBV)",

  ATH: "아테네 국제공항 (ATH)",
  JTR: "산토리니 공항 (JTR)",
  JMK: "미코노스 공항 (JMK)",
  HER: "이라클리온 국제공항 (HER)",
  RHO: "로도스 국제공항 (RHO)",

  DXB: "두바이 국제공항 (DXB)",
  AUH: "아부다비 국제공항 (AUH)",
  SHJ: "샤르자 국제공항 (SHJ)",
  AAN: "알 아인 국제공항 (AAN)",
  FJR: "푸자이라 국제공항 (FJR)",

  LIS: "리스본 공항 (LIS)",
  OPO: "포르투 공항 (OPO)",
  FAO: "파로 공항 (FAO)",
  FNC: "마데이라 공항 (FNC)",

  ARN: "스톡홀름 알란다 공항 (ARN)",
  GOT: "예테보리 란드베터 공항 (GOT)",
  MMX: "말뫼 공항 (MMX)",
  UME: "우메오 공항 (UME)",
  LLA: "룰레오 공항 (LLA)",

  AMS: "암스테르담 스키폴 공항 (AMS)",
  RTM: "로테르담 헤이그 공항 (RTM)",
  MST: "마스트리흐트 아헨 공항 (MST)",

  OSL: "오슬로 가르데르모엔 공항 (OSL)",
  BGO: "베르겐 플레슬란드 공항 (BGO)",
  TOS: "트롬쇠 공항 (TOS)",
  SVG: "스타방에르 솔라 공항 (SVG)",
  TRD: "트론헤임 베르네스 공항 (TRD)",

  EZE: "에세이사 국제공항 (EZE)",
  COR: "인헤니에로 타라벨라 공항 (COR)",
  ROS: "로사리오 국제공항 (ROS)",
  MDZ: "고버너 프란시스코 가브리엘리 국제공항 (MDZ)",
  USH: "말비나스 아르헨티나스 국제공항 (USH)",

  SCL: "아르투로 메리노 베니테스 국제공항 (SCL)",
  PMC: "엘 테푸알 공항 (PMC)",
  ZCO: "마케우에 공항 (ZCO)",
  CPO: "데시에르토 데 아타카마 공항 (CPO)",

  AKL: "오클랜드 공항 (AKL)",
  WLG: "웰링턴 공항 (WLG)",
  ZQN: "퀸스타운 공항 (ZQN)",
  CHC: "크라이스트처치 공항 (CHC)",
  ROT: "로토루아 공항 (ROT)",

  HEL: "헬싱키 반타 공항 (HEL)",
  RVN: "로바니에미 공항 (RVN)",
  TKU: "투르쿠 공항 (TKU)",
  TMP: "탐페레 피르칼라 공항 (TMP)",
  OUL: "오울루 공항 (OUL)",

  CPH: "코펜하겐 공항 (CPH)",
  AAR: "오르후스 공항 (AAR)",
  AAL: "알보르그 공항 (AAL)",
  EBJ: "에스비에르 공항 (EBJ)",

  BRU: "브뤼셀 공항 (BRU)",
  OST: "오스텐드 브뤼헤 국제공항 (OST)",
  ANR: "안트베르펜 공항 (ANR)",
  LGG: "리에주 공항 (LGG)",

  ZRH: "취리히 공항 (ZRH)",
  GVA: "제네바 공항 (GVA)",
  BRN: "베른 공항 (BRN)",

  VIE: "빈 국제공항 (VIE)",
  SZG: "잘츠부르크 공항 (SZG)",
  INN: "인스브루크 공항 (INN)",
  GRZ: "그라츠 공항 (GRZ)",
  KLU: "클라겐푸르트 공항 (KLU)",

  BUD: "부다페스트 페렌츠 리스트 국제공항 (BUD)",
  DEB: "데브레첸 국제공항 (DEB)",
  KSC: "코시체 국제공항 (KSC)",

  PRG: "프라하 바츨라프 하벨 공항 (PRG)",
  BRQ: "브르노 투라니 공항 (BRQ)",
  OSR: "오스트라바 레오스 야나체크 공항 (OSR)",

  WAW: "바르샤바 쇼팽 공항 (WAW)",
  KRK: "요한 바오로 2세 크라쿠프 발리체 국제공항 (KRK)",
  GDN: "그단스크 레흐 바웬사 공항 (GDN)",
  WRO: "브로츠와프 코페르니쿠스 공항 (WRO)",
  POZ: "포즈난 라비차 공항 (POZ)",

  OTP: "부쿠레슈티 헨리 코안더 국제공항 (OTP)",
  CLJ: "클루지 나포카 공항 (CLJ)",
  TSR: "티미쇼아라 트라이안 부이아 국제공항 (TSR)",
  CND: "콘스탄차 미하일 코글러니체아누 국제공항 (CND)",

  SOF: "소피아 공항 (SOF)",
  PDV: "플로브디프 공항 (PDV)",
  VAR: "바르나 공항 (VAR)",
  BOJ: "부르가스 공항 (BOJ)",
  GOZ: "고르나 오리야호비차 공항 (GOZ)",

  ZAG: "자그레브 공항 (ZAG)",
  DBV: "두브로브니크 공항 (DBV)",
  SPU: "스플리트 공항 (SPU)",
  ZAD: "자다르 공항 (ZAD)",
  RJK: "리예카 공항 (RJK)",

  BTS: "브라티슬라바 공항 (BTS)",
  ILZ: "즐리나 공항 (ILZ)",
  // KSC: "코시체 국제공항 (KSC)",

  LJU: "류블랴나 요제 푸츠니크 공항 (LJU)",
  MBX: "마리보르 에드바르드 루스잔 공항 (MBX)",
  // LJU: "류블랴나 요제 푸츠니크 공항 (LJU)",
  TRS: "트리에스테 프리울리 베네치아 줄리아 공항 (TRS)",

  TLV: "벤구리온 국제공항 (TLV)",
  HFA: "하이파 공항 (HFA)",
};

export const internationalAirportsWithCity = {
  파리: { name: "샤를 드골 공항", code: "CDG" },
  니스: { name: "니스 코트다쥐르 공항", code: "NCE" },
  리옹: { name: "리옹 생텍쥐페리 공항", code: "LYS" },
  마르세유: { name: "마르세유 프로방스 공항", code: "MRS" },
  보르도: { name: "보르도 메리냑 공항", code: "BOD" },

  도쿄: { name: "나리타 국제공항", code: "NRT" },
  교토: { name: "오사카 국제공항", code: "ITM" },
  오사카: { name: "간사이 국제공항", code: "KIX" },
  후쿠오카: { name: "후쿠오카 공항", code: "FUK" },
  삿포로: { name: "신치토세 공항", code: "CTS" },

  뉴욕: { name: "존 F. 케네디 국제공항", code: "JFK" },
  로스앤젤레스: { name: "로스앤젤레스 국제공항", code: "LAX" },
  샌프란시스코: { name: "샌프란시스코 국제공항", code: "SFO" },
  라스베이거스: { name: "해리 리드 국제공항", code: "LAS" },
  마이애미: { name: "마이애미 국제공항", code: "MIA" },

  런던: { name: "히드로 공항", code: "LHR" },
  에든버러: { name: "에든버러 공항", code: "EDI" },
  맨체스터: { name: "맨체스터 공항", code: "MAN" },
  리버풀: { name: "리버풀 존 레논 공항", code: "LPL" },
  옥스퍼드: { name: "옥스퍼드 공항", code: "OXF" },

  로마: { name: "피우미치노 국제공항", code: "FCO" },
  베네치아: { name: "베네치아 마르코폴로 공항", code: "VCE" },
  피렌체: { name: "피렌체 공항", code: "FLR" },
  밀라노: { name: "밀라노 말펜사 공항", code: "MXP" },
  나폴리: { name: "나폴리 국제공항", code: "NAP" },

  바르셀로나: { name: "바르셀로나 엘프라트 공항", code: "BCN" },
  마드리드: { name: "마드리드 바라하스 공항", code: "MAD" },
  세비야: { name: "세비야 공항", code: "SVQ" },
  그라나다: { name: "페데리코 가르시아 로르카 그라나다 공항", code: "GRX" },
  발렌시아: { name: "발렌시아 공항", code: "VLC" },

  베를린: { name: "베를린 브란덴부르크 공항", code: "BER" },
  뮌헨: { name: "뮌헨 공항", code: "MUC" },
  프랑크푸르트: { name: "프랑크푸르트 공항", code: "FRA" },
  함부르크: { name: "함부르크 공항", code: "HAM" },
  쾰른: { name: "쾰른 본 공항", code: "CGN" },

  베이징: { name: "베이징 수도 국제공항", code: "PEK" },
  상하이: { name: "상하이 푸동 국제공항", code: "PVG" },
  광저우: { name: "광저우 바이윈 국제공항", code: "CAN" },
  시안: { name: "시안 셴양 국제공항", code: "XIY" },
  청두: { name: "청두 솽류 국제공항", code: "CTU" },

  시드니: { name: "시드니 킹스포드 스미스 공항", code: "SYD" },
  멜버른: { name: "멜버른 공항", code: "MEL" },
  브리즈번: { name: "브리즈번 공항", code: "BNE" },
  퍼스: { name: "퍼스 공항", code: "PER" },
  애들레이드: { name: "애들레이드 공항", code: "ADL" },

  토론토: { name: "토론토 피어슨 국제공항", code: "YYZ" },
  밴쿠버: { name: "밴쿠버 국제공항", code: "YVR" },
  몬트리올: { name: "몬트리올 피에르 엘리오트 트뤼도 국제공항", code: "YUL" },
  "퀘벡 시티": { name: "퀘벡 시티 장 르사쥬 국제공항", code: "YQB" },
  오타와: { name: "오타와 맥도날드 카르티에 국제공항", code: "YOW" },

  모스크바: { name: "셰레메티예보 국제공항", code: "SVO" },
  상트페테르부르크: { name: "풀코보 공항", code: "LED" },
  노보시비르스크: { name: "톨마체보 공항", code: "OVB" },
  카잔: { name: "카잔 국제공항", code: "KZN" },
  소치: { name: "소치 국제공항", code: "AER" },

  리우데자네이루: { name: "리우데자네이루 갈레앙 국제공항", code: "GIG" },
  상파울루: { name: "상파울루 과룰류스 국제공항", code: "GRU" },
  브라질리아: { name: "브라질리아 국제공항", code: "BSB" },
  살바도르: { name: "살바도르 국제공항", code: "SSA" },
  "포르투 알레그리": { name: "포르투 알레그리 살가도 필류 국제공항", code: "POA" },

  델리: { name: "인디라 간디 국제공항", code: "DEL" },
  뭄바이: { name: "차트라파티 시바지 마하라지 국제공항", code: "BOM" },
  아그라: { name: "아그라 공항", code: "AGR" },
  자이푸르: { name: "자이푸르 국제공항", code: "JAI" },
  벵갈루루: { name: "켐페고우다 국제공항", code: "BLR" },

  이스탄불: { name: "이스탄불 공항", code: "IST" },
  앙카라: { name: "에센보아 국제공항", code: "ESB" },
  안탈리아: { name: "안탈리아 공항", code: "AYT" },
  카파도키아: { name: "네브셰히르 카파도키아 공항", code: "NAV" },
  이즈미르: { name: "이즈미르 아드난 멘데레스 공항", code: "ADB" },

  카이로: { name: "카이로 국제공항", code: "CAI" },
  알렉산드리아: { name: "알렉산드리아 보르그 엘 아랍 공항", code: "HBE" },
  루크소르: { name: "룩소르 국제공항", code: "LXR" },
  아스완: { name: "아스완 국제공항", code: "ASW" },
  "샤름 엘 셰이크": { name: "샤름 엘 셰이크 국제공항", code: "SSH" },

  케이프타운: { name: "케이프타운 국제공항", code: "CPT" },
  요하네스버그: { name: "오리버 탐보 국제공항", code: "JNB" },
  더반: { name: "킹 샤카 국제공항", code: "DUR" },
  프리토리아: { name: "프리토리아 원더붐 공항", code: "PRY" },
  "포트 엘리자베스": { name: "포트 엘리자베스 공항", code: "PLZ" },

  방콕: { name: "수완나품 국제공항", code: "BKK" },
  치앙마이: { name: "치앙마이 국제공항", code: "CNX" },
  푸켓: { name: "푸켓 국제공항", code: "HKT" },
  파타야: { name: "우타파오 국제공항", code: "UTP" },
  끄라비: { name: "끄라비 국제공항", code: "KBV" },

  아테네: { name: "아테네 국제공항", code: "ATH" },
  산토리니: { name: "산토리니 공항", code: "JTR" },
  미코노스: { name: "미코노스 공항", code: "JMK" },
  크레타: { name: "이라클리온 공항", code: "HER" },
  로도스: { name: "로도스 국제공항", code: "RHO" },

  두바이: { name: "두바이 국제공항", code: "DXB" },
  아부다비: { name: "아부다비 국제공항", code: "AUH" },
  샤르자: { name: "샤르자 국제공항", code: "SHJ" },
  "알 아인": { name: "알 아인 국제공항", code: "AAN" },
  푸자이라: { name: "푸자이라 국제공항", code: "FJR" },

  리스본: { name: "리스본 공항", code: "LIS" },
  포르투: { name: "포르투 공항", code: "OPO" },
  파로: { name: "파로 공항", code: "FAO" },
  신트라: { name: "리스본 공항", code: "LIS" },
  마데이라: { name: "마데이라 공항", code: "FNC" },

  스톡홀름: { name: "스톡홀름 알란다 공항", code: "ARN" },
  예테보리: { name: "예테보리 란드베터 공항", code: "GOT" },
  말뫼: { name: "말뫼 공항", code: "MMX" },
  우메오: { name: "우메오 공항", code: "UME" },
  룰레오: { name: "룰레오 공항", code: "LLA" },

  암스테르담: { name: "암스테르담 스키폴 공항", code: "AMS" },
  로테르담: { name: "로테르담 헤이그 공항", code: "RTM" },
  헤이그: { name: "로테르담 헤이그 공항", code: "RTM" },
  위트레흐트: { name: "암스테르담 스키폴 공항", code: "AMS" },
  마스트리흐트: { name: "마스트리흐트 아헨 공항", code: "MST" },

  오슬로: { name: "오슬로 가르데르모엔 공항", code: "OSL" },
  베르겐: { name: "베르겐 플레슬란드 공항", code: "BGO" },
  트롬쇠: { name: "트롬쇠 공항", code: "TOS" },
  스타방에르: { name: "스타방에르 솔라 공항", code: "SVG" },
  트론헤임: { name: "트론헤임 베르네스 공항", code: "TRD" },

  부에노스아이레스: { name: "에세이사 미니스트로 피스타리니 국제공항", code: "EZE" },
  코르도바: { name: "코르도바 인헤니에로 타라벨라 국제공항", code: "COR" },
  로사리오: { name: "로사리오 말비나스 아르헨티나스 국제공항", code: "ROS" },
  멘도사: { name: "멘도사 프란시스코 가브리엘리 국제공항", code: "MDZ" },
  우수아이아: { name: "우수아이아 말비나스 아르헨티나스 국제공항", code: "USH" },

  산티아고: { name: "산티아고 아르투로 메리노 베니테스 국제공항", code: "SCL" },
  발파라이소: { name: "산티아고 아르투로 메리노 베니테스 국제공항", code: "SCL" },
  "푸에르토 몬트": { name: "푸에르토 몬트 엘 테푸알 공항", code: "PMC" },
  푸콘: { name: "마케우에 공항", code: "ZCO" },
  아타카마: { name: "데시에르토 데 아타카마 공항", code: "CPO" },

  오클랜드: { name: "오클랜드 공항", code: "AKL" },
  웰링턴: { name: "웰링턴 공항", code: "WLG" },
  퀸스타운: { name: "퀸스타운 공항", code: "ZQN" },
  크라이스트처치: { name: "크라이스트처치 공항", code: "CHC" },
  로토루아: { name: "로토루아 공항", code: "ROT" },

  헬싱키: { name: "헬싱키 반타 공항", code: "HEL" },
  로바니에미: { name: "로바니에미 공항", code: "RVN" },
  투르쿠: { name: "투르쿠 공항", code: "TKU" },
  탐페레: { name: "탐페레 피르칼라 공항", code: "TMP" },
  오울루: { name: "오울루 공항", code: "OUL" },

  코펜하겐: { name: "코펜하겐 공항", code: "CPH" },
  오덴세: { name: "코펜하겐 공항", code: "CPH" },
  오르후스: { name: "오르후스 공항", code: "AAR" },
  알보르그: { name: "알보르그 공항", code: "AAL" },
  에스비에르: { name: "에스비에르 공항", code: "EBJ" },

  브뤼셀: { name: "브뤼셀 공항", code: "BRU" },
  브뤼헤: { name: "오스텐드 브뤼헤 국제공항", code: "OST" },
  안트베르펜: { name: "안트베르펜 공항", code: "ANR" },
  겐트: { name: "브뤼셀 공항", code: "BRU" },
  리에주: { name: "리에주 공항", code: "LGG" },

  취리히: { name: "취리히 공항", code: "ZRH" },
  제네바: { name: "제네바 공항", code: "GVA" },
  베른: { name: "베른 공항", code: "BRN" },
  루체른: { name: "취리히 공항", code: "ZRH" },
  인터라켄: { name: "취리히 공항", code: "ZRH" },

  빈: { name: "빈 국제공항", code: "VIE" },
  잘츠부르크: { name: "잘츠부르크 공항", code: "SZG" },
  인스브루크: { name: "인스브루크 공항", code: "INN" },
  그라츠: { name: "그라츠 공항", code: "GRZ" },
  클라겐푸르트: { name: "클라겐푸르트 공항", code: "KLU" },

  부다페스트: { name: "부다페스트 페렌츠 리스트 국제공항", code: "BUD" },
  데브레첸: { name: "데브레첸 국제공항", code: "DEB" },
  세게드: { name: "부다페스트 페렌츠 리스트 국제공항", code: "BUD" },
  미슈콜츠: { name: "코시체 국제공항", code: "KSC" },
  페치: { name: "페치 포가니 공항", code: "PEV" },

  프라하: { name: "프라하 바츨라프 하벨 공항", code: "PRG" },
  브르노: { name: "브르노 투라니 공항", code: "BRQ" },
  플젠: { name: "프라하 바츨라프 하벨 공항", code: "PRG" },
  오스트라바: { name: "오스트라바 레오스 야나체크 공항", code: "OSR" },
  올로모우츠: { name: "브르노 투라니 공항", code: "BRQ" },

  바르샤바: { name: "바르샤바 쇼팽 공항", code: "WAW" },
  크라쿠프: { name: "요한 바오로 2세 크라쿠프 발리체 국제공항", code: "KRK" },
  그단스크: { name: "그단스크 레흐 바웬사 공항", code: "GDN" },
  브로츠와프: { name: "브로츠와프 코페르니쿠스 공항", code: "WRO" },
  포즈난: { name: "포즈난 라비차 공항", code: "POZ" },

  부쿠레슈티: { name: "부쿠레슈티 헨리 코안더 국제공항", code: "OTP" },
  클루지나포카: { name: "클루지 나포카 공항", code: "CLJ" },
  티미쇼아라: { name: "티미쇼아라 트라이안 부이아 국제공항", code: "TSR" },
  브라쇼브: { name: "부쿠레슈티 헨리 코안더 국제공항", code: "OTP" },
  콘스탄차: { name: "콘스탄차 미하일 코글러니체아누 국제공항", code: "CND" },

  소피아: { name: "소피아 공항", code: "SOF" },
  플로브디프: { name: "플로브디프 공항", code: "PDV" },
  바르나: { name: "바르나 공항", code: "VAR" },
  부르가스: { name: "부르가스 공항", code: "BOJ" },
  벨리코타르노보: { name: "고르나 오리야호비차 공항", code: "GOZ" },

  자그레브: { name: "자그레브 공항", code: "ZAG" },
  두브로브니크: { name: "두브로브니크 공항", code: "DBV" },
  스플리트: { name: "스플리트 공항", code: "SPU" },
  자다르: { name: "자다르 공항", code: "ZAD" },
  리예카: { name: "리예카 공항", code: "RJK" },

  브라티슬라바: { name: "브라티슬라바 공항", code: "BTS" },
  코시체: { name: "코시체 국제공항", code: "KSC" },
  트르나바: { name: "브라티슬라바 공항", code: "BTS" },
  즐리나: { name: "즐리나 공항", code: "ILZ" },
  니트라: { name: "브라티슬라바 공항", code: "BTS" },

  류블랴나: { name: "류블랴나 요제 푸츠니크 공항", code: "LJU" },
  마리보르: { name: "마리보르 에드바르드 루스잔 공항", code: "MBX" },
  체리케: { name: "류블랴나 요제 푸츠니크 공항", code: "LJU" },
  포스토이나: { name: "류블랴나 요제 푸츠니크 공항", code: "LJU" },
  피란: { name: "트리에스테 프리울리 베네치아 줄리아 공항", code: "TRS" },

  예루살렘: { name: "벤구리온 국제공항", code: "TLV" },
  텔아비브: { name: "벤구리온 국제공항", code: "TLV" },
  하이파: { name: "하이파 공항", code: "HFA" },
  베들레헴: { name: "벤구리온 국제공항", code: "TLV" },
  나사렛: { name: "벤구리온 국제공항", code: "TLV" },
};

export const internationalAirportsKo = {
  파리: "샤를 드골 공항 (CDG)",
  니스: "니스 코트다쥐르 공항 (NCE)",
  리옹: "리옹 생텍쥐페리 공항 (LYS)",
  마르세유: "마르세유 프로방스 공항 (MRS)",
  보르도: "보르도 메리냑 공항 (BOD)",

  도쿄: "나리타 국제공항 (NRT)",
  교토: "오사카 국제공항 (ITM)",
  오사카: "간사이 국제공항 (KIX)",
  후쿠오카: "후쿠오카 공항 (FUK)",
  삿포로: "신치토세 공항 (CTS)",

  뉴욕: "존 F. 케네디 국제공항 (JFK)",
  로스앤젤레스: "로스앤젤레스 국제공항 (LAX)",
  샌프란시스코: "샌프란시스코 국제공항 (SFO)",
  라스베이거스: "해리 리드 국제공항 (LAS)",
  마이애미: "마이애미 국제공항 (MIA)",

  런던: "히드로 공항 (LHR)",
  에든버러: "에든버러 공항 (EDI)",
  맨체스터: "맨체스터 공항 (MAN)",
  리버풀: "리버풀 존 레논 공항 (LPL)",
  옥스퍼드: "옥스퍼드 공항 (OXF)",

  로마: "피우미치노 국제공항 (FCO)",
  베네치아: "베네치아 마르코폴로 공항 (VCE)",
  피렌체: "피렌체 공항 (FLR)",
  밀라노: "밀라노 말펜사 공항 (MXP)",
  나폴리: "나폴리 국제공항 (NAP)",

  바르셀로나: "바르셀로나 엘프라트 공항 (BCN)",
  마드리드: "마드리드 바라하스 공항 (MAD)",
  세비야: "세비야 공항 (SVQ)",
  그라나다: "페데리코 가르시아 로르카 그라나다 공항 (GRX)",
  발렌시아: "발렌시아 공항 (VLC)",

  베를린: "베를린 브란덴부르크 공항 (BER)",
  뮌헨: "뮌헨 공항 (MUC)",
  프랑크푸르트: "프랑크푸르트 공항 (FRA)",
  함부르크: "함부르크 공항 (HAM)",
  쾰른: "쾰른 본 공항 (CGN)",

  베이징: "베이징 수도 국제공항 (PEK)",
  상하이: "상하이 푸동 국제공항 (PVG)",
  광저우: "광저우 바이윈 국제공항 (CAN)",
  시안: "시안 셴양 국제공항 (XIY)",
  청두: "청두 솽류 국제공항 (CTU)",

  시드니: "시드니 킹스포드 스미스 공항 (SYD)",
  멜버른: "멜버른 공항 (MEL)",
  브리즈번: "브리즈번 공항 (BNE)",
  퍼스: "퍼스 공항 (PER)",
  애들레이드: "애들레이드 공항 (ADL)",

  토론토: "토론토 피어슨 국제공항 (YYZ)",
  밴쿠버: "밴쿠버 국제공항 (YVR)",
  몬트리올: "몬트리올 피에르 엘리오트 트뤼도 국제공항 (YUL)",
  "퀘벡 시티": "퀘벡 시티 장 르사쥬 국제공항 (YQB)",
  오타와: "오타와 맥도날드 카르티에 국제공항 (YOW)",

  모스크바: "셰레메티예보 국제공항 (SVO)",
  상트페테르부르크: "풀코보 공항 (LED)",
  노보시비르스크: "톨마체보 공항 (OVB)",
  카잔: "카잔 국제공항 (KZN)",
  소치: "소치 국제공항 (AER)",

  리우데자네이루: "리우데자네이루 갈레앙 국제공항 (GIG)",
  상파울루: "상파울루 과룰류스 국제공항 (GRU)",
  브라질리아: "브라질리아 국제공항 (BSB)",
  살바도르: "살바도르 국제공항 (SSA)",
  "포르투 알레그리": "포르투 알레그리 살가도 필류 국제공항 (POA)",

  델리: "인디라 간디 국제공항 (DEL)",
  뭄바이: "차트라파티 시바지 마하라지 국제공항 (BOM)",
  아그라: "아그라 공항 (AGR)",
  자이푸르: "자이푸르 국제공항 (JAI)",
  벵갈루루: "켐페고우다 국제공항 (BLR)",

  이스탄불: "이스탄불 공항 (IST)",
  앙카라: "에센보아 국제공항 (ESB)",
  안탈리아: "안탈리아 공항 (AYT)",
  카파도키아: "네브셰히르 카파도키아 공항 (NAV)",
  이즈미르: "이즈미르 아드난 멘데레스 공항 (ADB)",

  카이로: "카이로 국제공항 (CAI)",
  알렉산드리아: "알렉산드리아 보르그 엘 아랍 공항 (HBE)",
  루크소르: "룩소르 국제공항 (LXR)",
  아스완: "아스완 국제공항 (ASW)",
  "샤름 엘 셰이크": "샤름 엘 셰이크 국제공항 (SSH)",

  케이프타운: "케이프타운 국제공항 (CPT)",
  요하네스버그: "오리버 탐보 국제공항 (JNB)",
  더반: "킹 샤카 국제공항 (DUR)",
  프리토리아: "프리토리아 원더붐 공항 (PRY)",
  "포트 엘리자베스": "포트 엘리자베스 공항 (PLZ)",

  방콕: "수완나품 국제공항 (BKK)",
  치앙마이: "치앙마이 국제공항 (CNX)",
  푸켓: "푸켓 국제공항 (HKT)",
  파타야: "우타파오 국제공항 (UTP)",
  끄라비: "끄라비 국제공항 (KBV)",

  아테네: "아테네 국제공항 (ATH)",
  산토리니: "산토리니 공항 (JTR)",
  미코노스: "미코노스 공항 (JMK)",
  크레타: "이라클리온 공항 (HER)",
  로도스: "로도스 국제공항 (RHO)",

  두바이: "두바이 국제공항 (DXB)",
  아부다비: "아부다비 국제공항 (AUH)",
  샤르자: "샤르자 국제공항 (SHJ)",
  "알 아인": "알 아인 국제공항 (AAN)",
  푸자이라: "푸자이라 국제공항 (FJR)",

  리스본: "리스본 공항 (LIS)",
  포르투: "포르투 공항 (OPO)",
  파로: "파로 공항 (FAO)",
  신트라: "리스본 공항 (LIS)",
  마데이라: "마데이라 공항 (FNC)",

  스톡홀름: "스톡홀름 알란다 공항 (ARN)",
  예테보리: "예테보리 란드베터 공항 (GOT)",
  말뫼: "말뫼 공항 (MMX)",
  우메오: "우메오 공항 (UME)",
  룰레오: "룰레오 공항 (LLA)",

  암스테르담: "암스테르담 스키폴 공항 (AMS)",
  로테르담: "로테르담 헤이그 공항 (RTM)",
  헤이그: "로테르담 헤이그 공항 (RTM)",
  위트레흐트: "암스테르담 스키폴 공항 (AMS)",
  마스트리흐트: "마스트리흐트 아헨 공항 (MST)",

  오슬로: "오슬로 가르데르모엔 공항 (OSL)",
  베르겐: "베르겐 플레슬란드 공항 (BGO)",
  트롬쇠: "트롬쇠 공항 (TOS)",
  스타방에르: "스타방에르 솔라 공항 (SVG)",
  트론헤임: "트론헤임 베르네스 공항 (TRD)",

  부에노스아이레스: "에세이사 미니스트로 피스타리니 국제공항 (EZE)",
  코르도바: "코르도바 인헤니에로 타라벨라 국제공항 (COR)",
  로사리오: "로사리오 말비나스 아르헨티나스 국제공항 (ROS)",
  멘도사: "멘도사 프란시스코 가브리엘리 국제공항 (MDZ)",
  우수아이아: "우수아이아 말비나스 아르헨티나스 국제공항 (USH)",

  산티아고: "산티아고 아르투로 메리노 베니테스 국제공항 (SCL)",
  발파라이소: "산티아고 아르투로 메리노 베니테스 국제공항 (SCL)",
  "푸에르토 몬트": "푸에르토 몬트 엘 테푸알 공항 (PMC)",
  푸콘: "마케우에 공항 (ZCO)",
  아타카마: "데시에르토 데 아타카마 공항 (CPO)",

  오클랜드: "오클랜드 공항 (AKL)",
  웰링턴: "웰링턴 공항 (WLG)",
  퀸스타운: "퀸스타운 공항 (ZQN)",
  크라이스트처치: "크라이스트처치 공항 (CHC)",
  로토루아: "로토루아 공항 (ROT)",

  헬싱키: "헬싱키 반타 공항 (HEL)",
  로바니에미: "로바니에미 공항 (RVN)",
  투르쿠: "투르쿠 공항 (TKU)",
  탐페레: "탐페레 피르칼라 공항 (TMP)",
  오울루: "오울루 공항 (OUL)",

  코펜하겐: "코펜하겐 공항 (CPH)",
  오덴세: "코펜하겐 공항 (CPH)",
  오르후스: "오르후스 공항 (AAR)",
  알보르그: "알보르그 공항 (AAL)",
  에스비에르: "에스비에르 공항 (EBJ)",

  브뤼셀: "브뤼셀 공항 (BRU)",
  브뤼헤: "오스텐드 브뤼헤 국제공항 (OST)",
  안트베르펜: "안트베르펜 공항 (ANR)",
  겐트: "브뤼셀 공항 (BRU)",
  리에주: "리에주 공항 (LGG)",

  취리히: "취리히 공항 (ZRH)",
  제네바: "제네바 공항 (GVA)",
  베른: "베른 공항 (BRN)",
  루체른: "취리히 공항 (ZRH)",
  인터라켄: "취리히 공항 (ZRH)",

  빈: "빈 국제공항 (VIE)",
  잘츠부르크: "잘츠부르크 공항 (SZG)",
  인스브루크: "인스브루크 공항 (INN)",
  그라츠: "그라츠 공항 (GRZ)",
  클라겐푸르트: "클라겐푸르트 공항 (KLU)",

  부다페스트: "부다페스트 페렌츠 리스트 국제공항 (BUD)",
  데브레첸: "데브레첸 국제공항 (DEB)",
  세게드: "부다페스트 페렌츠 리스트 국제공항 (BUD)",
  미슈콜츠: "코시체 국제공항 (KSC)",
  페치: "페치 포가니 공항 (PEV)",

  프라하: "프라하 바츨라프 하벨 공항 (PRG)",
  브르노: "브르노 투라니 공항 (BRQ)",
  플젠: "프라하 바츨라프 하벨 공항 (PRG)",
  오스트라바: "오스트라바 레오스 야나체크 공항 (OSR)",
  올로모우츠: "브르노 투라니 공항 (BRQ)",

  바르샤바: "바르샤바 쇼팽 공항 (WAW)",
  크라쿠프: "요한 바오로 2세 크라쿠프 발리체 국제공항 (KRK)",
  그단스크: "그단스크 레흐 바웬사 공항 (GDN)",
  브로츠와프: "브로츠와프 코페르니쿠스 공항 (WRO)",
  포즈난: "포즈난 라비차 공항 (POZ)",

  부쿠레슈티: "부쿠레슈티 헨리 코안더 국제공항 (OTP)",
  클루지나포카: "클루지 나포카 공항 (CLJ)",
  티미쇼아라: "티미쇼아라 트라이안 부이아 국제공항 (TSR)",
  브라쇼브: "부쿠레슈티 헨리 코안더 국제공항 (OTP)",
  콘스탄차: "콘스탄차 미하일 코글러니체아누 국제공항 (CND)",

  소피아: "소피아 공항 (SOF)",
  플로브디프: "플로브디프 공항 (PDV)",
  바르나: "바르나 공항 (VAR)",
  부르가스: "부르가스 공항 (BOJ)",
  벨리코타르노보: "고르나 오리야호비차 공항 (GOZ)",

  자그레브: "자그레브 공항 (ZAG)",
  두브로브니크: "두브로브니크 공항 (DBV)",
  스플리트: "스플리트 공항 (SPU)",
  자다르: "자다르 공항 (ZAD)",
  리예카: "리예카 공항 (RJK)",

  브라티슬라바: "브라티슬라바 공항 (BTS)",
  코시체: "코시체 국제공항 (KSC)",
  트르나바: "브라티슬라바 공항 (BTS)",
  즐리나: "즐리나 공항 (ILZ)",
  니트라: "브라티슬라바 공항 (BTS)",

  류블랴나: "류블랴나 요제 푸츠니크 공항 (LJU)",
  마리보르: "마리보르 에드바르드 루스잔 공항 (MBX)",
  체리케: "류블랴나 요제 푸츠니크 공항 (LJU)",
  포스토이나: "류블랴나 요제 푸츠니크 공항 (LJU)",
  피란: "트리에스테 프리울리 베네치아 줄리아 공항 (TRS)",

  예루살렘: "벤구리온 국제공항 (TLV)",
  텔아비브: "벤구리온 국제공항 (TLV)",
  하이파: "하이파 공항 (HFA)",
  베들레헴: "벤구리온 국제공항 (TLV)",
  나사렛: "벤구리온 국제공항(TLV)",
};

export const internationalAirportsEn = {
  파리: "Charles de Gaulle Airport (CDG)",
  니스: "Nice Côte d'Azur Airport (NCE)",
  리옹: "Lyon-Saint Exupéry Airport (LYS)",
  마르세유: "Marseille Provence Airport (MRS)",
  보르도: "Bordeaux-Mérignac Airport (BOD)",

  도쿄: "Narita International Airport (NRT)",
  교토: "Osaka International Airport (ITM)",
  오사카: "Kansai International Airport (KIX)",
  후쿠오카: "Fukuoka Airport (FUK)",
  삿포로: "New Chitose Airport (CTS)",

  뉴욕: "John F. Kennedy International Airport (JFK)",
  로스앤젤레스: "Los Angeles International Airport (LAX)",
  샌프란시스코: "San Francisco International Airport (SFO)",
  라스베이거스: "McCarran International Airport (LAS)",
  마이애미: "Miami International Airport (MIA)",

  런던: "Heathrow Airport (LHR)",
  에든버러: "Edinburgh Airport (EDI)",
  맨체스터: "Manchester Airport (MAN)",
  리버풀: "Liverpool John Lennon Airport (LPL)",
  옥스퍼드: "Oxford Airport (OXF)",

  로마: "Leonardo da Vinci–Fiumicino Airport (FCO)",
  베네치아: "Venice Marco Polo Airport (VCE)",
  피렌체: "Florence Airport (FLR)",
  밀라노: "Milan Malpensa Airport (MXP)",
  나폴리: "Naples International Airport (NAP)",

  바르셀로나: "Barcelona–El Prat Airport (BCN)",
  마드리드: "Adolfo Suárez Madrid–Barajas Airport (MAD)",
  세비야: "Seville Airport (SVQ)",
  그라나다: "Federico García Lorca Granada Airport (GRX)",
  발렌시아: "Valencia Airport (VLC)",

  베를린: "Berlin Brandenburg Airport (BER)",
  뮌헨: "Munich Airport (MUC)",
  프랑크푸르트: "Frankfurt Airport (FRA)",
  함부르크: "Hamburg Airport (HAM)",
  쾰른: "Cologne Bonn Airport (CGN)",

  베이징: "Beijing Capital International Airport (PEK)",
  상하이: "Shanghai Pudong International Airport (PVG)",
  광저우: "Guangzhou Baiyun International Airport (CAN)",
  시안: "Xi'an Xianyang International Airport (XIY)",
  청두: "Chengdu Shuangliu International Airport (CTU)",

  시드니: "Sydney Kingsford Smith Airport (SYD)",
  멜버른: "Melbourne Airport (MEL)",
  브리즈번: "Brisbane Airport (BNE)",
  퍼스: "Perth Airport (PER)",
  애들레이드: "Adelaide Airport (ADL)",

  토론토: "Toronto Pearson International Airport (YYZ)",
  밴쿠버: "Vancouver International Airport (YVR)",
  몬트리올: "Montréal–Pierre Elliott Trudeau International Airport (YUL)",
  "퀘벡 시티": "Québec City Jean Lesage International Airport (YQB)",
  오타와: "Ottawa Macdonald-Cartier International Airport (YOW)",

  모스크바: "Sheremetyevo International Airport (SVO)",
  상트페테르부르크: "Pulkovo Airport (LED)",
  노보시비르스크: "Tolmachevo Airport (OVB)",
  카잔: "Kazan International Airport (KZN)",
  소치: "Sochi International Airport (AER)",

  리우데자네이루: "Rio de Janeiro–Galeão International Airport (GIG)",
  상파울루: "São Paulo–Guarulhos International Airport (GRU)",
  브라질리아: "Brasília International Airport (BSB)",
  살바도르: "Salvador International Airport (SSA)",
  "포르투 알레그리": "Salgado Filho International Airport (POA)",

  델리: "Indira Gandhi International Airport (DEL)",
  뭄바이: "Chhatrapati Shivaji Maharaj International Airport (BOM)",
  아그라: "Agra Airport (AGR)",
  자이푸르: "Jaipur International Airport (JAI)",
  벵갈루루: "Kempegowda International Airport (BLR)",

  이스탄불: "Istanbul Airport (IST)",
  앙카라: "Esenboğa International Airport (ESB)",
  안탈리아: "Antalya Airport (AYT)",
  카파도키아: "Nevşehir Kapadokya Airport (NAV)",
  이즈미르: "Adnan Menderes Airport (ADB)",

  카이로: "Cairo International Airport (CAI)",
  알렉산드리아: "Borg El Arab Airport (HBE)",
  루크소르: "Luxor International Airport (LXR)",
  아스완: "Aswan International Airport (ASW)",
  "샤름 엘 셰이크": "Sharm El Sheikh International Airport (SSH)",

  케이프타운: "Cape Town International Airport (CPT)",
  요하네스버그: "O. R. Tambo International Airport (JNB)",
  더반: "King Shaka International Airport (DUR)",
  프리토리아: "Wonderboom Airport (PRY)",
  "포트 엘리자베스": "Port Elizabeth Airport (PLZ)",

  방콕: "Suvarnabhumi Airport (BKK)",
  치앙마이: "Chiang Mai International Airport (CNX)",
  푸켓: "Phuket International Airport (HKT)",
  파타야: "U-Tapao International Airport (UTP)",
  끄라비: "Krabi International Airport (KBV)",

  아테네: "Athens International Airport (ATH)",
  산토리니: "Santorini (Thira) National Airport (JTR)",
  미코노스: "Mykonos Island National Airport (JMK)",
  크레타: "Heraklion International Airport (HER)",
  로도스: "Rhodes International Airport (RHO)",

  두바이: "Dubai International Airport (DXB)",
  아부다비: "Abu Dhabi International Airport (AUH)",
  샤르자: "Sharjah International Airport (SHJ)",
  "알 아인": "Al Ain International Airport (AAN)",
  푸자이라: "Fujairah International Airport (FJR)",

  리스본: "Lisbon Airport (LIS)",
  포르투: "Francisco Sá Carneiro Airport (OPO)",
  파로: "Faro Airport (FAO)",
  신트라: "Lisbon Airport (LIS)",
  마데이라: "Madeira Airport (FNC)",

  스톡홀름: "Stockholm Arlanda Airport (ARN)",
  예테보리: "Gothenburg Landvetter Airport (GOT)",
  말뫼: "Malmö Airport (MMX)",
  우메오: "Umeå Airport (UME)",
  룰레오: "Luleå Airport (LLA)",

  암스테르담: "Amsterdam Airport Schiphol (AMS)",
  로테르담: "Rotterdam The Hague Airport (RTM)",
  헤이그: "Rotterdam The Hague Airport (RTM)",
  위트레흐트: "Amsterdam Airport Schiphol (AMS)",
  마스트리흐트: "Maastricht Aachen Airport (MST)",

  오슬로: "Oslo Gardermoen Airport (OSL)",
  베르겐: "Bergen Airport, Flesland (BGO)",
  트롬쇠: "Tromsø Airport (TOS)",
  스타방에르: "Stavanger Airport, Sola (SVG)",
  트론헤임: "Trondheim Airport, Værnes (TRD)",

  부에노스아이레스: "Ministro Pistarini International Airport (EZE)",
  코르도바: "Ingeniero Aeronáutico Ambrosio L.V. Taravella International Airport (COR)",
  로사리오: "Rosario – Islas Malvinas International Airport (ROS)",
  멘도사: "Governor Francisco Gabrielli International Airport (MDZ)",
  우수아이아: "Ushuaia – Malvinas Argentinas International Airport (USH)",

  산티아고: "Comodoro Arturo Merino Benítez International Airport (SCL)",
  발파라이소: "Comodoro Arturo Merino Benítez International Airport (SCL)",
  "푸에르토 몬트": "El Tepual Airport (PMC)",
  푸콘: "Maquehue Airport (ZCO)",
  아타카마: "Desierto de Atacama Airport (CPO)",

  오클랜드: "Auckland Airport (AKL)",
  웰링턴: "Wellington Airport (WLG)",
  퀸스타운: "Queenstown Airport (ZQN)",
  크라이스트처치: "Christchurch Airport (CHC)",
  로토루아: "Rotorua Airport (ROT)",

  헬싱키: "Helsinki-Vantaa Airport (HEL)",
  로바니에미: "Rovaniemi Airport (RVN)",
  투르쿠: "Turku Airport (TKU)",
  탐페레: "Tampere–Pirkkala Airport (TMP)",
  오울루: "Oulu Airport (OUL)",

  코펜하겐: "Copenhagen Airport (CPH)",
  오덴세: "Copenhagen Airport (CPH)",
  오르후스: "Aarhus Airport (AAR)",
  알보르그: "Aalborg Airport (AAL)",
  에스비에르: "Esbjerg Airport (EBJ)",

  브뤼셀: "Brussels Airport (BRU)",
  브뤼헤: "Ostend-Bruges International Airport (OST)",
  안트베르펜: "Antwerp International Airport (ANR)",
  겐트: "Brussels Airport (BRU)",
  리에주: "Liège Airport (LGG)",

  취리히: "Zurich Airport (ZRH)",
  제네바: "Geneva Airport (GVA)",
  베른: "Bern Airport (BRN)",
  루체른: "Zurich Airport (ZRH)",
  인터라켄: "Zurich Airport (ZRH)",

  빈: "Vienna International Airport (VIE)",
  잘츠부르크: "Salzburg Airport (SZG)",
  인스브루크: "Innsbruck Airport (INN)",
  그라츠: "Graz Airport (GRZ)",
  클라겐푸르트: "Klagenfurt Airport (KLU)",

  부다페스트: "Budapest Ferenc Liszt International Airport (BUD)",
  데브레첸: "Debrecen International Airport (DEB)",
  세게드: "Budapest Ferenc Liszt International Airport (BUD)",
  미슈콜츠: "Košice International Airport (KSC)",
  페치: "Pécs-Pogány International Airport (PEV)",

  프라하: "Václav Havel Airport Prague (PRG)",
  브르노: "Brno–Tuřany Airport (BRQ)",
  플젠: "Václav Havel Airport Prague (PRG)",
  오스트라바: "Leoš Janáček Airport Ostrava (OSR)",
  올로모우츠: "Brno–Tuřany Airport (BRQ)",

  바르샤바: "Warsaw Chopin Airport (WAW)",
  크라쿠프: "John Paul II Kraków-Balice International Airport (KRK)",
  그단스크: "Gdańsk Lech Wałęsa Airport (GDN)",
  브로츠와프: "Copernicus Airport Wrocław (WRO)",
  포즈난: "Poznań–Ławica Airport (POZ)",

  부쿠레슈티: "Henri Coandă International Airport (OTP)",
  클루지나포카: "Cluj International Airport (CLJ)",
  티미쇼아라: "Timișoara Traian Vuia International Airport (TSR)",
  브라쇼브: "Henri Coandă International Airport (OTP)",
  콘스탄차: "Mihail Kogălniceanu International Airport (CND)",

  소피아: "Sofia Airport (SOF)",
  플로브디프: "Plovdiv Airport (PDV)",
  바르나: "Varna Airport (VAR)",
  부르가스: "Burgas Airport (BOJ)",
  벨리코타르노보: "Gorna Oryahovitsa Airport (GOZ)",

  자그레브: "Zagreb Airport (ZAG)",
  두브로브니크: "Dubrovnik Airport (DBV)",
  스플리트: "Split Airport (SPU)",
  자다르: "Zadar Airport (ZAD)",
  리예카: "Rijeka Airport (RJK)",

  브라티슬라바: "Bratislava Airport (BTS)",
  코시체: "Košice International Airport (KSC)",
  트르나바: "Bratislava Airport (BTS)",
  즐리나: "Žilina Airport (ILZ)",
  니트라: "Bratislava Airport (BTS)",

  류블랴나: "Ljubljana Jože Pučnik Airport (LJU)",
  마리보르: "Maribor Edvard Rusjan Airport (MBX)",
  체리케: "Ljubljana Jože Pučnik Airport (LJU)",
  포스토이나: "Ljubljana Jože Pučnik Airport (LJU)",
  피란: "Trieste – Friuli Venezia Giulia Airport (TRS)",

  예루살렘: "Ben Gurion International Airport (TLV)",
  텔아비브: "Ben Gurion International Airport (TLV)",
  하이파: "Haifa Airport (HFA)",
  베들레헴: "Ben Gurion International Airport (TLV)",
  나사렛: "Ben Gurion International Airport (TLV)",
};
